import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function About() {
  return (
    <div className="">
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="lg:h-[40vh] h-[20vh] w-screen bg-[#0000009e] flex flex-col justify-center items-center gap-2">
        <h1 className="text-white font-medium lg:text-4xl text-2xl">
          About Us
        </h1>
        <div className="text-white">
          <Link href={"/"}>
            <a className="hover:underline ">Home</a>
          </Link>{" "}
          / <text className="text-orange-600">About</text>
        </div>
      </section>
      <section className="lg:p-20 p-10 ">
        <div className="lg:grid grid-cols-2">
          <div className="lg:p-10">
            <h1 className="lg:text-4xl font-medium">
              THE DUBOIS MEMORIAL CENTER
            </h1>
            <span className="text-gray-600 lg:text-lg">
              {`The Centre is a complex of four major buildings which include the
              home where Dr. DuBois spent his last years, an Administrative
              building, the Marcus Garvey Guest House and the tomb of Dr. DuBois
              and his dear wife Shirley Graham DuBois.`}
            </span>
          </div>
          <div className="relative h-96">
            <Image src="/zion.jpeg" layout="fill" />
          </div>
        </div>
      </section>
    </div>
  );
}
