import {
  ClockIcon,
  MailIcon,
  MapIcon,
  PhoneIcon,
} from "@heroicons/react/outline";
import Head from "next/head";
import Image from "next/image";

export default function Contact() {
  return (
    <div className="">
      <Head>
        <title>Dubois Memorial Center | Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="h-[60vh] bg-blue-500 w-screen"></section>
      <section className="lg:p-20 ">
        <div className="flex flex-col justify-center items-center gap-2 mb-4">
          <span className="text-gray-500">CONTACT</span>
          <span className="font-thin italic lg:text-4xl">
            <text className="text-orange-600">NEED HELP?</text> CONTACT US
          </span>
        </div>
        <div className="lg:grid grid-cols-2 lg:gap-5">
          <div className="lg:p-8 flex flex-row gap-5 bg-orange-50">
            <div className="lg:h-14 lg:w-14 rounded-full bg-orange-600 text-gray-100 flex flex-col justify-center items-center">
              <MapIcon className="h-8 w-8" />
            </div>
            <div className="flex flex-col justify-start items-start gap-">
              <h1 className="lg:text-2xl font-bold text-gray-600">
                Our Address
              </h1>
              <span className=" text-gray-800">
                Dubois Center, 1 Second Circular Rd, Accra
              </span>
            </div>
          </div>
          <div className="lg:p-8 flex flex-row gap-5 bg-orange-50">
            <div className="lg:h-14 lg:w-14 rounded-full bg-orange-600 text-gray-100 flex flex-col justify-center items-center">
              <MailIcon className="h-8 w-8" />
            </div>
            <div className="flex flex-col justify-start items-start gap-">
              <h1 className="lg:text-2xl font-bold text-gray-600">Email Us</h1>
              <span className=" text-gray-800">info@dubois</span>
            </div>
          </div>
          <div className="lg:p-8 flex flex-row gap-5 bg-orange-50">
            <div className="lg:h-14 lg:w-14 rounded-full bg-orange-600 text-gray-100 flex flex-col justify-center items-center">
              <PhoneIcon className="h-8 w-8" />
            </div>
            <div className="flex flex-col justify-start items-start gap-">
              <h1 className="lg:text-2xl font-bold text-gray-600">Call Us</h1>
              <span className=" text-gray-800">+233 12 3456 789</span>
            </div>
          </div>
          <div className="lg:p-8 flex flex-row gap-5 bg-orange-50">
            <div className="lg:h-14 lg:w-14 rounded-full bg-orange-600 text-gray-100 flex flex-col justify-center items-center">
              <ClockIcon className="h-8 w-8" />
            </div>
            <div className="flex flex-col justify-start items-start gap-">
              <h1 className="lg:text-2xl font-bold text-gray-600">
                Opening Hours
              </h1>
              <span className=" text-gray-800">
                <strong>Mon - Fri </strong> 8:00AM - 5:00PM;{" "}
                <strong>{"Sat & Sun "}</strong> Closed
              </span>
            </div>
          </div>
        </div>
      </section>
      <section className="lg:px-20 w-screen">
      <iframe className="w-full lg:h-[400px] shadow-md" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15883.59462918059!2d-0.1709516!3d5.5819962!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x63c8e7cdf33c2377!2sW.E.B.%20DuBois%20Centre%20in%20Accra!5e0!3m2!1sen!2sgh!4v1657489961258!5m2!1sen!2sgh"  style={{border:0}} allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </section>
      <section className="lg:p-20 w-screen">
        <form className="bg-white shadow-md w-full flex flex-col gap-3 lg:p-20">
          <div className="lg:grid grid-cols-2 gap-4">
            <div className="flex flex-col gap-1">
              <label>Full name</label>
              <input
                type={"text"}
                className="h-12 p-2 border-[1.5px] border-gray-400"
                placeholder="John"
              />
            </div>
            <div className="flex flex-col gap-1">
              <label>Email</label>
              <input
                type={"email"}
                className="h-12 p-2 border-[1.5px] border-gray-400"
                placeholder="Doe"
              />
            </div>
          </div>
          <div className="flex flex-col gap-1">
            <label>Subject</label>
            <input
              type={"text"}
              className="h-12 p-2 border-[1.5px] border-gray-400"
            />
          </div>
          <div className="flex flex-col gap-1">
            <label>Message</label>
            <textarea className="h-24 p-2 border-[1.5px] border-gray-400"></textarea>
          </div>
          <button type="submit" className="rounded-full h-12 px-10 self-center mt-5 w-min bg-orange-600 text-white flex flex-col justify-center items-center">
            Submit
          </button>
        </form>
      </section>
    </div>
  );
}
