import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import GallerySwiper from "../components/gallery_swiper";

export default function Gallery() {
  let [isOpen, setIsOpen] = useState(false);

  function closeModal() {
    setIsOpen(false);
  }

  function openModal() {
    setIsOpen(true);
  }
  return (
    <div className="">
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className=" w-screen lg:p-20 p-10">
        <h1 className="text-4xl font-medium text-gray-700 text-center">
          GALLERY
        </h1>
        <h1
          data-aos="fade-up"
          data-aos-delay="600"
          className="font-thin lg:text-4xl text-center"
        >
          CHECK OUR GALLERY{" "}
          <text className="text-orange-600">FROM RECENT EVENTS</text>
        </h1>
      </section>
      <section
        data-aos="fade-up"
        data-aos-delay="900"
        className="lg:px-4 px-2 lg:pb-20 pb-10 grid grid-cols-2 lg:grid-cols-4 gap-1 relative"
      >
        <div className="h-52 w-full relative" onClick={openModal}>
          <Image
            src={"/zion.jpeg"}
            layout={"fill"}
            className="hover:scale-125 duration-1000 hover:ease-in-out"
          />
        </div>
        <div className="h-52 w-full relative" onClick={openModal}>
          <Image
            src={"/zion.jpeg"}
            layout={"fill"}
            className="hover:scale-125 duration-1000 hover:ease-in-out"
          />
        </div>
        <div className="h-52 w-full relative" onClick={openModal}>
          <Image
            src={"/zion.jpeg"}
            layout={"fill"}
            className="hover:scale-125 duration-1000 hover:ease-in-out"
          />
        </div>
        <div className="h-52 w-full relative" onClick={openModal}>
          <Image
            src={"/zion.jpeg"}
            layout={"fill"}
            className="hover:scale-125 duration-1000 hover:ease-in-out"
          />
        </div>
        <GallerySwiper isOpen={isOpen} closeModal={closeModal} />
      </section>
    </div>
  );
}
