import Head from 'next/head'
import Image from 'next/image'

export default function Gallery() {
  return (
    <div className=''>
      <Head>
        <title>Dubois Memorial Center | Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='h-screen w-screen'>

      </section>
    </div>
  )
}
