import Head from "next/head";
import Image from "next/image";
import HomeSwiper from "../components/homeSwiper";
import HomeGallery from "../components/home_gallery";
import TestimonialSwiper from "../components/testimonialSwiper";
import Link from "next/link";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Dubois Memorial Center | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className=" w-screen">
        <HomeSwiper />
      </section>
      <section className="lg:p-20 bg-orange-50">
        <div className="flex flex-col gap-2 mb-10">
          <span
            data-aos="fade-up"
            data-aos-delay="300"
            className="text-center text-gray-500"
          >
            TESTIMONIALS
          </span>
          <h1
            data-aos="fade-up"
            data-aos-delay="600"
            className="font-thin lg:text-4xl text-center"
          >
            WHAT ARE THEY{" "}
            <text className="text-orange-600">SAYING ABOUT US</text>
          </h1>
        </div>
        <TestimonialSwiper />
      </section>
      <section className="lg:p-20 ">
        <div className="flex flex-col gap-2 mb-10">
          <span
            data-aos="fade-up"
            data-aos-delay="300"
            className="text-center text-gray-500"
          >
            GALLERY
          </span>
          <h1
            data-aos="fade-up"
            data-aos-delay="600"
            className="font-thin lg:text-4xl text-center"
          >
            CHECK <text className="text-orange-600">OUR GALLERY</text>
          </h1>
        </div>
        <HomeGallery />
        <div className="flex flex-row justify-center">
          <Link href="/gallery">
            <a
              data-aos="fade-up"
              data-aos-delay="900"
              className="rounded-md h-12 shadow-md hover:text-orange-600 hover:bg-white hover:border-2 hover:border-orange-600 bg-orange-600 text-white px-5 flex flex-col justify-center items-center mt-10"
            >
              View more
            </a>
          </Link>
        </div>
      </section>
    </div>
  );
}
